name = "bionic-bob"
main = "dist/index.mjs"

account_id = "1db9917825f95bd7c7e1468383b8e3a4"
workers_dev = true
# route = ""

compatibility_date = "2022-05-28"
compatibility_flags = []


[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true

[vars]
# SLACK_BOT_TOKEN
