name = "bionic-bob"
main = "dist/index.mjs"

account_id = "1db9917825f95bd7c7e1468383b8e3a4"
workers_dev = true
# route = ""

compatibility_date = "2022-05-28"
compatibility_flags = []

kv_namespaces = [
    { binding = "BIONIC_BOB_TRACKING", id = "7b1c6c43503b4aa78dfba8cf0a18c0ad" }
]

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true

[vars]
# SLACK_BOT_TOKEN
# EASYPOST_API_KEY
# ONSHAPE_SECRET_KEY
# ONSHAPE_ACCESS_KEY

